enum constants {
    SET_SHOP_LIST = "SET_SHOP_LIST",
    SET_OPEN_SHOPS = "SET_OPEN_SHOPS",
    SET_ACTIVE_SHOP = "SET_ACTIVE_SHOP",

    SET_CATEGORIES = "SET_CATEGORIES",
    SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY",

    SET_PRODUCT = "SET_PRODUCT",
    SET_MODIFICATIONS = "SET_MODIFICATIONS",
    SET_ACTIVE_PRODUCT = "SET_ACTIVE_PRODUCT",
    SET_ACTIVE_MODE = "SET_ACTIVE_MODE",

    SET_BASKET_ID = "SET_BASKET_ID",
    SET_BASKET_PRODUCTS = "SET_BASKET_PRODUCTS",
    SET_BASKET_SHOP = "SET_BASKET_SHOP",
    UPDATE_BASKET_PRODUCT = "UPDATE_BASKET_PRODUCT",
    ADD_BASKET_PRODUCT = "ADD_BASKET_PRODUCT",
    DELETE_BASKET_PRODUCT = "DELETE_BASKET_PRODUCT"
}

export default constants;
